
sudo: false
language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'

script:
  - sbt assembly

notifications:
  email:
    - andy.hicks@digital.hmrc.gov.uk
    
